---
kind: pipeline
type: kubernetes
name: migrate-image

platform:
  os: linux
  arch: aarch64

trigger:
  branches:
    - v2.11.x
  event:
    - push

steps:
- name: build
  image: golang:1.14.7
  commands:
  - apt-get update -qq
  - apt-get install -y -qq gcc jq zip conntrack
  - apt-get install -y -qq libudev-dev
  - apt-get install -y -qq rsync
  - SRC_REPO="$(pwd)"
  - DST_REPO="$GOPATH/src/github.com/openebs/upgrade"
  - if [ "$SRC_REPO" != "$DST_REPO" ]; then
  - echo "Copying from $SRC_REPO to $DST_REPO"
  - echo "But first, get the git revision from $SRC_REPO"
  - export GIT_COMMIT="$(git rev-parse HEAD)"
  - echo $GIT_COMMIT >> $${SRC_REPO}/GITCOMMIT
  - export RELEASE_TAG="2.11.0"
  - mkdir -p $DST_REPO
  - echo "rsync -az $SRC_REPO/ $DST_REPO/"
  - rsync -az "$SRC_REPO/" "$DST_REPO/"
  - export TRAVIS_BUILD_DIR=$DST_REPO
  - cd $DST_REPO
  - fi
  - make migrate
  - ls -lrt "$(pwd)/bin/migrate/"
  - cp bin/migrate/migrate $SRC_REPO/build/migrate/
  - ls -lrt "$SRC_REPO/build/migrate/"

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: zebardy/openebs-migrate
    context: /drone/src/build/migrate/
    dockerfile: /drone/src/build/migrate/Dockerfile
    tag: "2.11.0"
    build_args:
    - DBUILD_DATE=${DRONE_BUILD_STARTED}
    - DBUILD_REPO_URL=${DRONE_REPO_LINK}
    - DBUILD_SITE_URL=https://openebs.io
    - ARCH=${DRONE_STAGE_ARCH}
